// UI copy only. Dataset values, identifiers and server narratives are unchanged.
// Each row is [Russian, English, Kazakh]; {n} denotes an existing display value.
export const messages = [
  ['Аким на 5 часов', 'Akim for 5 hours', '5 сағатқа әкім'],
  ['Аким на 5 часов, наверх', 'Akim for 5 hours, back to top', '5 сағатқа әкім, жоғарыға'],
  ['АКИМ', 'AKIM', 'ӘКІМ'], ['НА 5 ЧАСОВ', 'FOR 5 HOURS', '5 САҒАТҚА'],
  ['Разделы страницы', 'Page sections', 'Бет бөлімдері'],
  ['Решения', 'Decisions', 'Шешімдер'], ['Районы', 'Districts', 'Аудандар'], ['AI-анализ', 'AI analysis', 'AI талдауы'], ['Сравнение', 'Compare', 'Салыстыру'],
  ['API недоступен', 'API unavailable', 'API қолжетімсіз'], ['Подключаем API', 'Connecting to API', 'API-ге қосылуда'], ['API подключён', 'API connected', 'API қосылды'],
  ['ГОРОДСКОЙ СИМУЛЯТОР · HACKALEM AI', 'CITY SIMULATOR · HACKALEM AI', 'ҚАЛА СИМУЛЯТОРЫ · HACKALEM AI'],
  ['Пять решений.', 'Five decisions.', 'Бес шешім.'], ['Один город.', 'One city.', 'Бір қала.'],
  ['Распределите 100 условных единиц между городскими инициативами и увидьте, как изменится качество жизни пяти районов за два условных года.', 'Allocate 100 budget units to city initiatives and see how quality of life changes across five districts over two simulated years.', 'Қала бастамаларына 100 шартты бірлікті бөліп, екі шартты жылда бес ауданның өмір сапасы қалай өзгеретінін көріңіз.'],
  ['Собрать сценарий', 'Build a scenario', 'Сценарий құру'],
  ['Все данные синтетические. Это учебная модель, не прогноз для Астаны.', 'All data is synthetic. This is a learning model, not a forecast for Astana.', 'Барлық деректер жасанды. Бұл — оқу моделі, Астанаға арналған болжам емес.'],
  ['Ваш рассчитанный сценарий', 'Your evaluated scenario', 'Есептелген сценарийіңіз'], ['Единое исходное состояние', 'Shared starting point', 'Бірыңғай бастапқы жағдай'],
  ['{0} к исходному Score', '{0} vs. initial Score', 'Бастапқы Score-мен салыстырғанда {0}'],
  ['одинаково для всех участников', 'the same for every participant', 'барлық қатысушы үшін бірдей'],
  ['Исходный Score', 'Initial Score', 'Бастапқы Score'], ['Критических значений', 'Critical values', 'Шекті мәннен төмен'], ['Остаток бюджета', 'Budget remaining', 'Бюджет қалдығы'],
  ['Загружаем город', 'Loading the city', 'Қала жүктелуде'], ['Получаем каталог, исходные показатели и состояние сервера.', 'Loading the catalog, initial indicators and server status.', 'Каталог, бастапқы көрсеткіштер және сервер күйі жүктелуде.'],
  ['Не удалось подключиться к backend', 'Could not connect to the server', 'Серверге қосылу мүмкін болмады'],
  ['Проверьте, что API запущен и адрес в', 'Check that the API is running and the address in', 'API іске қосылғанын және'],
  ['верный.', 'is correct.', 'файлындағы мекенжайдың дұрыстығын тексеріңіз.'],
  ['Повторить подключение', 'Reconnect', 'Қайта қосылу'], ['5 районов', '5 districts', '5 аудан'], ['10 показателей', '10 indicators', '10 көрсеткіш'], ['14 мероприятий', '14 measures', '14 шара'], ['8 кварталов', '8 quarters', '8 тоқсан'], ['Версия данных:', 'Dataset version:', 'Деректер нұсқасы:'],
  ['Сценарий не рассчитан', 'Scenario not evaluated', 'Сценарий есептелмеді'], ['Повторить', 'Retry', 'Қайталау'],
  ['Проверяйте решения на данных, а не на догадках.', 'Test your decisions against data.', 'Шешімдерді деректер арқылы тексеріңіз.'],
  ['Синтетический датасет · Score считает сервер · AI не меняет выбранные меры', 'Synthetic dataset · Server-calculated Score · AI does not change your choices', 'Жасанды деректер · Score серверде есептеледі · AI таңдаған шараларды өзгертпейді'],
  ['01 / РЕШЕНИЯ', '01 / DECISIONS', '01 / ШЕШІМДЕР'], ['Соберите свой сценарий', 'Build your scenario', 'Өз сценарийіңізді құрыңыз'],
  ['Пять разных мер, минимум три направления, бюджет до', 'Five distinct measures, at least three areas, a budget of up to', 'Бес түрлі шара, кемінде үш бағыт, бюджет шегі:'],
  ['единиц. Районные меры действуют в одном районе, городские — во всех пяти.', 'units. District measures affect one district; city measures affect all five.', 'бірлік. Аудандық шаралар бір ауданда, қалалық шаралар бес ауданда да қолданылады.'],
  ['Пример из задания', 'Load example', 'Тапсырмадағы мысал'], ['Очистить', 'Clear', 'Тазарту'], ['Предварительная стоимость', 'Estimated cost', 'Алдын ала құны'], ['Использовано бюджета', 'Budget used', 'Жұмсалған бюджет'],
  ['Перерасход: {0} ед.', 'Over budget: {0} units', 'Артық шығын: {0} бірлік'], ['Осталось: {0} ед. Остаток не повышает Score.', 'Remaining: {0} units. Unused budget does not increase Score.', 'Қалдығы: {0} бірлік. Қалдық Score-ды арттырмайды.'],
  ['Направления · не более', 'Areas · up to', 'Бағыттар · әрқайсысына ең көбі'], ['мер на каждое', 'measures per area', 'шара'],
  ['Выбор пяти управленческих решений', 'Select five management decisions', 'Бес басқару шешімін таңдау'], ['Мероприятие', 'Measure', 'Шара'], ['Выберите меру', 'Select a measure', 'Шараны таңдаңыз'], ['до учёта лага', 'before the time lag', 'кідірісті есепке алғанға дейін'], ['Район', 'District', 'Аудан'],
  ['Весь город', 'Entire city', 'Бүкіл қала'], ['весь город', 'entire city', 'бүкіл қала'], ['город', 'city', 'қала'], ['Городская мера', 'City measure', 'Қалалық шара'], ['Районная мера', 'District measure', 'Аудандық шара'], ['· лаг', '· lag', '· кідіріс'], ['кв.', 'qtr.', 'тоқ.'], ['ед.', 'units', 'бірл.'], ['Мера не выбрана', 'No measure selected', 'Шара таңдалмаған'],
  ['Проверьте набор решений', 'Review your decisions', 'Шешімдер жиынын тексеріңіз'], ['✓ Набор допустим:', '✓ Valid scenario:', '✓ Жиын жарамды:'], ['решений, бюджет соблюдён. Итог проверит сервер.', 'decisions within budget. The server will validate the scenario.', 'шешім, бюджет сақталған. Нәтижені сервер тексереді.'], ['Рассчитываем…', 'Calculating…', 'Есептелуде…'], ['Рассчитать и получить AI-анализ', 'Calculate and get AI analysis', 'Есептеу және AI талдауын алу'], ['Все вычисления Score выполняет backend.', 'All Score calculations run on the server.', 'Score толықтай серверде есептеледі.'],
  ['Транспорт', 'Transport', 'Көлік'], ['Экология', 'Environment', 'Экология'], ['Социальная сфера', 'Social services', 'Әлеуметтік сала'], ['Безопасность', 'Safety', 'Қауіпсіздік'], ['Городские сервисы', 'City services', 'Қалалық қызметтер'],
  ['Есиль', 'Esil', 'Есіл'], ['Алматы', 'Almaty', 'Алматы'], ['Сарыарка', 'Saryarka', 'Сарыарқа'], ['Байконур', 'Baikonur', 'Байқоңыр'], ['Нура', 'Nura', 'Нұра'],
  ['Выделенные полосы для автобусов', 'Dedicated bus lanes', 'Автобустарға арналған жолақтар'], ['Умные светофоры', 'Smart traffic lights', 'Ақылды бағдаршамдар'], ['Линия ЛРТ / расширение', 'LRT line / expansion', 'LRT желісі / кеңейту'], ['Парк / сквер', 'Park / public garden', 'Саябақ / гүлбақ'], ['Перевод частного сектора на чистое топливо', 'Clean fuel for private housing', 'Жеке тұрғын үйлерді таза отынға көшіру'], ['Городская программа озеленения и ветрозащитных полос', 'City greening and windbreak program', 'Қаланы көгалдандыру және желден қорғайтын белдеулер бағдарламасы'], ['Школа + детсад (модульное строительство)', 'School + kindergarten (modular construction)', 'Мектеп + балабақша (модульдік құрылыс)'], ['Центр семейного здоровья / поликлиника', 'Family health center / clinic', 'Отбасылық денсаулық орталығы / емхана'], ['Дворовые спорт-хабы', 'Neighborhood sports hubs', 'Ауладағы спорт орталықтары'], ['Освещение и камеры (расширение Safe City)', 'Lighting and cameras (Safe City expansion)', 'Жарықтандыру және камералар (Safe City кеңейту)'], ['Безопасные переходы и школьные зоны', 'Safe crossings and school zones', 'Қауіпсіз өткелдер және мектеп аймақтары'], ['Единая цифровая платформа обращений', 'Unified digital platform for resident requests', 'Өтініштерге арналған бірыңғай цифрлық платформа'], ['Модернизация тепло- и водосетей', 'Heating and water network upgrades', 'Жылу және су желілерін жаңғырту'], ['Аварийные бригады ЖКХ + раннее оповещение', 'Emergency utility teams + early warnings', 'ТКШ апаттық бригадалары + ерте ескерту'],
  ['02 / ПОКАЗАТЕЛИ', '02 / INDICATORS', '02 / КӨРСЕТКІШТЕР'], ['Что изменилось в районах', 'What changed in each district', 'Аудандарда не өзгерді'], ['Один исходный набор для всех сценариев. Нажмите на район, чтобы увидеть все десять показателей.', 'All scenarios use the same starting data. Select a district to see all ten indicators.', 'Барлық сценарийдің бастапқы деректері бірдей. Он көрсеткішті көру үшін ауданды таңдаңыз.'], ['значение ниже', 'a value below', 'мәні'], ['— критическое', 'is critical', 'мәнінен төмен болса — сыни'], ['Выберите район', 'Select a district', 'Ауданды таңдаңыз'], ['{0} к базе', '{0} vs. baseline', 'Бастапқыға қатысты {0}'], ['исходный балл', 'initial score', 'бастапқы балл'], ['Критических: {0}', 'Critical: {0}', 'Сыни мәндер: {0}'], ['Без критических значений', 'No critical values', 'Сыни мәндер жоқ'],
  ['Состав итогового Score', 'Final Score breakdown', 'Қорытынды Score құрамы'], ['Средний балл города · 70%', 'City average · 70%', 'Қаланың орташа балы · 70%'], ['Слабейший район · 30%', 'Lowest-scoring district · 30%', 'Ең төмен балды аудан · 30%'], ['Штраф за показатели ниже', 'Penalty for indicators below', 'Көрсеткіштердің төмен болуына айып шегі:'], ['Итог: 0,7 × средний балл + 0,3 × балл слабейшего района − число критических показателей.', 'Total: 0.7 × city average + 0.3 × lowest district score − number of critical indicators.', 'Нәтиже: 0,7 × орташа балл + 0,3 × ең төмен аудан балы − сыни көрсеткіштер саны.'],
  ['РАЙОН КРУПНЫМ ПЛАНОМ', 'DISTRICT IN DETAIL', 'АУДАН ТОЛЫҒЫРАҚ'], ['Балл:', 'Score:', 'Балл:'], ['Показатели района', 'District indicators —', 'Аудан көрсеткіштері:'], [': исходные и после решений', ': before and after decisions', ': бастапқы және шешімдерден кейінгі'], ['Показатель', 'Indicator', 'Көрсеткіш'], ['До', 'Before', 'Дейін'], ['После', 'After', 'Кейін'], ['Изменение', 'Change', 'Өзгеріс'], ['Состояние', 'Status', 'Күйі'], ['Ниже', 'Below', 'Төмен:'], ['От', 'At least', 'Кемінде'],
  ['Разгрузка дорог', 'Traffic flow', 'Жол жүктемесін азайту'], ['Общественный транспорт', 'Public transport', 'Қоғамдық көлік'], ['Озеленение', 'Green spaces', 'Көгалдандыру'], ['Качество воздуха', 'Air quality', 'Ауа сапасы'], ['Школы и детсады', 'Schools and kindergartens', 'Мектептер мен балабақшалар'], ['Медицинская помощь', 'Healthcare', 'Медициналық көмек'], ['Безопасность улиц', 'Street safety', 'Көше қауіпсіздігі'], ['Безопасность дорог', 'Road safety', 'Жол қауіпсіздігі'], ['Надёжность ЖКХ', 'Utility reliability', 'ТКШ сенімділігі'], ['Обращения жителей', 'Resident requests', 'Тұрғындардың өтініштері'],
  ['100 означает лучшее состояние. Эффекты и синергии складываются до ограничения каждого показателя диапазоном 0–100.', '100 is the best state. Effects and synergies are added before each indicator is capped to 0–100.', '100 — ең жақсы жағдай. Әсерлер мен синергиялар қосылған соң әр көрсеткіш 0–100 аралығымен шектеледі.'],
  ['Как сработали меры', 'How the measures worked', 'Шаралар қалай әсер етті'], ['· реализовано', '· realized', '· іске асқаны'], ['% за', '% over', '% /'], ['Синергии', 'Synergies', 'Синергиялар'], ['В этом наборе синергии не сработали.', 'No synergies were activated in this scenario.', 'Бұл жиында синергиялар іске қосылмады.'], ['Показанные эффекты даны до ограничения 0–100. Они не складываются напрямую в Score.', 'Effects are shown before the 0–100 cap. They cannot be added directly to Score.', 'Әсерлер 0–100 шектеуіне дейін көрсетілген. Оларды Score-ға тікелей қосуға болмайды.'],
  ['03 / АНАЛИЗ', '03 / ANALYSIS', '03 / ТАЛДАУ'], ['Почему получился такой результат', 'Why you got this result', 'Неліктен осындай нәтиже шықты'], ['AI объясняет рассчитанный сервером сценарий. Score и стоимость определяет только модель расчёта.', 'AI explains the server-evaluated scenario. Only the calculation model determines Score and cost.', 'AI сервер есептеген сценарийді түсіндіреді. Score мен құнды тек есептеу моделі анықтайды.'], ['Считаем сценарий и готовим объяснение…', 'Evaluating the scenario and preparing an explanation…', 'Сценарий есептеліп, түсіндірме дайындалуда…'], ['Ответ AI может занять до 12 секунд; при ошибке сервер вернёт явно обозначенный шаблон.', 'AI may take up to 12 seconds; on failure, the server returns a clearly labeled template.', 'AI жауабы 12 секундқа дейін созылуы мүмкін; қате болса, сервер анық белгіленген үлгіні қайтарады.'],
  ['AI: шаблон (mock)', 'AI: template (mock)', 'AI: үлгі (mock)'], ['AI: шаблон (fallback)', 'AI: template (fallback)', 'AI: үлгі (fallback)'], ['AI: режим неизвестен', 'AI: unknown mode', 'AI: режимі белгісіз'], ['Ответ модели', 'Model response', 'Модель жауабы'], ['Проверенный ответ из кэша', 'Verified cached response', 'Кэштегі тексерілген жауап'], ['Шаблонное объяснение', 'Template explanation', 'Үлгілік түсіндірме'], ['Сильные стороны', 'Strengths', 'Артықшылықтар'], ['Риски и компромиссы', 'Risks and trade-offs', 'Тәуекелдер мен ымыралар'], ['Что проверить дальше', 'What to explore next', 'Келесі тексерілетін қадамдар'], ['Текст AI помогает понять результат. Цифры альтернатив рассчитаны сервером.', 'AI text helps explain the result. Alternative figures are calculated by the server.', 'AI мәтіні нәтижені түсінуге көмектеседі. Балама сандарды сервер есептейді.'], ['Повторить анализ', 'Repeat analysis', 'Талдауды қайталау'], ['Анализ появится после расчёта', 'Analysis appears after calculation', 'Талдау есептеуден кейін пайда болады'], ['Выберите пять мер и нажмите «Рассчитать и получить AI-анализ».', 'Select five measures and click “Calculate and get AI analysis”.', 'Бес шараны таңдап, «Есептеу және AI талдауын алу» түймесін басыңыз.'],
  ['Серверный разбор и описание компромиссов предоставлены на русском языке.', 'The server analysis and trade-off descriptions are provided in Russian.', 'Сервер талдауы мен ымыралардың сипаттамасы орыс тілінде берілген.'],
  ['ПРОВЕРЕНО СЕРВЕРОМ', 'VERIFIED BY THE SERVER', 'СЕРВЕР ТЕКСЕРГЕН'], ['Следующий шаг', 'Next step', 'Келесі қадам'], ['Проверены все допустимые замены одной меры. Одна карточка может быть лучшей по нескольким критериям. «Применить» изменит форму и пересчитает сценарий; прежние советы исчезнут.', 'All valid single-measure replacements were checked. One option may lead on several criteria. “Apply” updates the form and recalculates the scenario; previous advice is cleared.', 'Бір шараны ауыстырудың барлық жарамды нұсқалары тексерілді. Бір нұсқа бірнеше өлшем бойынша үздік болуы мүмкін. «Қолдану» форманы өзгертіп, сценарийді қайта есептейді; бұрынғы кеңестер жойылады.'],
  ['Лучший Score', 'Best Score', 'Үздік Score'], ['Самая дешёвая из улучшающих', 'Lowest-cost improvement', 'Ең арзан жақсарту'], ['Минимум критических показателей', 'Fewest critical indicators', 'Сыни көрсеткіштер ең аз'], ['Заменить', 'Replace', 'Ауыстыру'], ['На', 'With', 'Орнына'], ['Стоимость:', 'Cost:', 'Құны:'], ['Остаток:', 'Remaining:', 'Қалдығы:'], ['Критических:', 'Critical:', 'Сыни мәндер:'], ['Ухудшения относительно текущего набора', 'Declines compared with the current scenario', 'Қазіргі жиынмен салыстырғандағы нашарлау'], ['Снижения отдельных показателей нет.', 'No individual indicators decline.', 'Жеке көрсеткіштер төмендемейді.'], ['Применить', 'Apply', 'Қолдану'], ['Применить: {0}', 'Apply: {0}', 'Қолдану: {0}'], ['{0} «{1}» ({2})', '{0} “{1}” ({2})', '{0} «{1}» ({2})'], ['Среди замен одной меры сервер не нашёл варианта с более высоким Score. Это не означает, что другие наборы из пяти мер хуже.', 'The server found no single-measure replacement with a higher Score. Other five-measure combinations may still perform better.', 'Сервер бір шараны ауыстыру арқылы Score-ды арттыратын нұсқа таппады. Бес шараның басқа жиыны жақсырақ болуы мүмкін.'],
  ['04 / СРАВНЕНИЕ', '04 / COMPARISON', '04 / САЛЫСТЫРУ'], ['Проверьте другой набор', 'Try another scenario', 'Басқа жиынды тексеріңіз'], ['Сохраните результат в этом браузере, измените меры и рассчитайте снова. Оба результата считаются из одной исходной базы.', 'Save the result in this browser, change your measures and calculate again. Both results use the same starting data.', 'Нәтижені осы браузерде сақтап, шараларды өзгертіңіз де, қайта есептеңіз. Екі нәтиже де бір бастапқы деректерден есептеледі.'], ['Заменить сохранённый', 'Replace saved result', 'Сақталғанды ауыстыру'], ['Сохранить для сравнения', 'Save for comparison', 'Салыстыру үшін сақтау'], ['Сохранённый набор использует другую версию данных. Для честного сравнения сохраните новый результат.', 'The saved scenario uses a different dataset version. Save a new result for a fair comparison.', 'Сақталған жиында деректердің басқа нұсқасы бар. Дұрыс салыстыру үшін жаңа нәтижені сақтаңыз.'], ['Удалить старый набор', 'Delete old scenario', 'Ескі жиынды жою'], ['СОХРАНЁННЫЙ СЦЕНАРИЙ', 'SAVED SCENARIO', 'САҚТАЛҒАН СЦЕНАРИЙ'], ['Убрать', 'Remove', 'Алып тастау'], ['Разница с сохранённым набором', 'Difference from saved scenario', 'Сақталған жиыннан айырмасы'], ['пункта Score', 'Score points', 'Score ұпайы'], ['Сравнение двух рассчитанных сценариев', 'Comparison of two evaluated scenarios', 'Екі есептелген сценарийді салыстыру'], ['Сохранённый', 'Saved', 'Сақталған'], ['Текущий', 'Current', 'Қазіргі'], ['Стоимость', 'Cost', 'Құны'], ['Слабейший район', 'Lowest-scoring district', 'Ең төмен балды аудан'], ['Критические показатели', 'Critical indicators', 'Сыни көрсеткіштер'], ['Наборы имеют версию данных', 'Dataset version for both scenarios:', 'Екі жиынның деректер нұсқасы:'], ['. Сравнение использует только ответы сервера.', '. Comparison uses only server responses.', '. Салыстыру тек сервер жауаптарына негізделген.'], ['Сценарий сохранён. Измените одну из мер или район и рассчитайте новый набор.', 'Scenario saved. Change a measure or district and evaluate the new scenario.', 'Сценарий сақталды. Бір шараны не ауданды өзгертіп, жаңа жиынды есептеңіз.'], ['Первый результат ещё не сохранён', 'No result saved yet', 'Алғашқы нәтиже әлі сақталмаған'], ['После расчёта сохраните его здесь. Например, перенесите M7 из Нуры в Есиль и сравните Score.', 'Save your result here after calculating. For example, move M7 from Nura to Esil and compare Score.', 'Есептеуден кейін нәтижені осында сақтаңыз. Мысалы, M7 шарасын Нұрадан Есілге көшіріп, Score-ды салыстырыңыз.'],
  ['Сервер не ответил вовремя. Попробуйте ещё раз.', 'The server timed out. Please try again.', 'Сервер уақытында жауап бермеді. Қайта көріңіз.'], ['Нет связи с сервером. Проверьте backend и повторите запрос.', 'Cannot reach the server. Check the backend and retry.', 'Сервермен байланыс жоқ. Backend-ті тексеріп, сұрауды қайталаңыз.'], ['Сервер вернул ответ в неожиданном формате.', 'The server returned an unexpected response format.', 'Сервер күтпеген пішімде жауап берді.'], ['Ошибка сервера ({0}).', 'Server error ({0}).', 'Сервер қатесі ({0}).'], ['Не удалось рассчитать сценарий.', 'Could not evaluate the scenario.', 'Сценарийді есептеу мүмкін болмады.'], ['Версия данных изменилась. Обновите страницу и рассчитайте набор снова.', 'The dataset version changed. Refresh the page and calculate again.', 'Деректер нұсқасы өзгерді. Бетті жаңартып, жиынды қайта есептеңіз.'], ['Сервер предложил недопустимый набор мер. Обновите страницу и попробуйте снова.', 'The server proposed an invalid scenario. Refresh the page and try again.', 'Сервер жарамсыз шаралар жиынын ұсынды. Бетті жаңартып, қайта көріңіз.'], ['Этот совет устарел. Рассчитайте текущий набор заново.', 'This advice is outdated. Recalculate the current scenario.', 'Бұл кеңес ескірген. Қазіргі жиынды қайта есептеңіз.'], ['Набор изменился после анализа. Рассчитайте его заново.', 'The scenario changed after analysis. Recalculate it.', 'Талдаудан кейін жиын өзгерді. Оны қайта есептеңіз.'],
  ['Выберите ровно {0} мероприятий.', 'Select exactly {0} measures.', 'Дәл {0} шара таңдаңыз.'], ['Выбрано неизвестное мероприятие.', 'Unknown measure selected.', 'Белгісіз шара таңдалған.'], ['{0}: для городской меры район не выбирается.', '{0}: city measures do not require a district.', '{0}: қалалық шара үшін аудан таңдалмайды.'], ['{0}: выберите район.', '{0}: select a district.', '{0}: ауданды таңдаңыз.'], ['{0} выбран несколько раз. Каждая мера доступна только один раз.', '{0} was selected more than once. Each measure can only be used once.', '{0} бірнеше рет таңдалған. Әр шараны тек бір рет таңдауға болады.'], ['Бюджет превышен на {0} ед. Уберите или замените меру.', 'Budget exceeded by {0} units. Remove or replace a measure.', 'Бюджет {0} бірлікке артты. Шараны алып тастаңыз немесе ауыстырыңыз.'], ['{0}: не более {1} мер.', '{0}: at most {1} measures.', '{0}: ең көбі {1} шара.'], ['Нельзя одновременно выбирать BRT и ЛРТ, даже в разных районах.', 'BRT and LRT cannot be selected together, even in different districts.', 'BRT мен LRT-ді әртүрлі аудандарда болса да бірге таңдауға болмайды.'], ['Парк и школа в одном районе конфликтуют за участок.', 'A park and a school in the same district compete for land.', 'Бір аудандағы саябақ пен мектеп бір жер учаскесіне таласады.'], ['Чистое топливо и модернизация сетей в одном районе дублируют программу.', 'Clean fuel and network upgrades duplicate a program in the same district.', 'Бір аудандағы таза отын мен желілерді жаңғырту бір бағдарламаны қайталайды.'],
];

const dictionaries = Object.fromEntries(['ru', 'en', 'kk'].map((locale, index) => [locale, new Map(messages.filter(([key]) => !key.includes('{')).map((row) => [row[0], row[index]]))]));
const escape = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const templates = messages.filter(([key]) => key.includes('{')).map((row) => ({ row, pattern: new RegExp(`^${row[0].split(/\{\d+\}/).map(escape).join('(.+?)')}$`) }));

export function translate(text, locale = 'ru', depth = 0) {
  if (typeof text !== 'string' || locale === 'ru' || !dictionaries[locale] || depth > 4) return text;
  const key = text.trim();
  const exact = dictionaries[locale].get(key);
  if (exact !== undefined) return text.replace(key, () => exact);
  for (const { row, pattern } of templates) {
    const match = key.match(pattern);
    if (match) return text.replace(key, () => row[locale === 'en' ? 1 : 2].replace(/\{(\d+)\}/g, (_, n) => translate(match[Number(n) + 1], locale, depth + 1)));
  }
  // Composite option labels and saved scenarios keep IDs and numbers verbatim.
  if (text.includes(' · ')) return text.split(' · ').map((part) => translate(part, locale, depth + 1)).join(' · ');
  const districtLabel = key.match(/^(M\d+) (Есиль|Алматы|Сарыарка|Байконур|Нура|город)$/);
  if (districtLabel) return `${districtLabel[1]} ${translate(districtLabel[2], locale, depth + 1)}`;
  const units = key.match(/^(\d+(?:\.\d+)?) ед\.$/);
  if (units) return `${units[1]} ${translate('ед.', locale)}`;
  return text;
}
